### ISSUE TITLE
Support Use of Logo

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/pelerine#1]
How do you feel about adding support for a site logo?

In my experiments with logos on the site using this theme, the logo is displayed really big. 

Seems like it might be an easy win to provide add some default css for a standard size logo. I may be able to work on a PR for this, if you are interested.

See:

![Home___Backdrop](https://user-images.githubusercontent.com/3144571/89371088-f23a2200-d6a7-11ea-9fba-6fc59a7c6322.png)

or

![Home___Backdrop](https://user-images.githubusercontent.com/3144571/89371151-1dbd0c80-d6a8-11ea-8153-c3fd7cdf3dc7.png)

**Comment by stpaultim** [comment]
I wanted to fix this for my own purposes, so I create a PR. 
https://github.com/backdrop-contrib/pelerine/pull/2

I welcome improvements on the PR (or feel free to ignore it, if you don't like the idea). 

I'd explain what I did, but I think it's pretty clear from CSS. 

Oh well, here it is.

I've limited the size of the logo element in the header block. 
On small screens, I wrap the elements in the header, set a minimum width (so they don't keep shrinking), and then center them over each other. 

![Home___Simplo](https://user-images.githubusercontent.com/3144571/89375800-13a10b00-d6b4-11ea-8e90-9f59296ec17f.png)

![Home___Simplo](https://user-images.githubusercontent.com/3144571/89375831-287d9e80-d6b4-11ea-8f52-7de943a8bdc6.png)

**Comment by indigoxela** [comment]
@stpaultim obviously I didn't have logo images in mind when creating this theme. Of course, better support makes sense.

Does the latest commit work for you?

**Comment by stpaultim** [comment]
Yes, I've done some very basic testing and it seems to work, I will test more very soon. I'd love it if you looked at the CSS to see if I've missed an obviously better solution or put my changes in the wrong place.

**Comment by indigoxela** [comment]
To avoid misunderstandings: *my* commits here in the dev version. :wink:

**Comment by stpaultim** [comment]
@indigoxela - Nice work. Thanks. 

Your layout of the header with the logo is different from mine. I expect you are aware of that. I think I preferred my choices, but that is purely a subjective decision. I assume you prefer the choices you made and you are the maintainer. I think that both are fine and work better than before. 

Just to be clear about the differences. 

Your PR aligns the title to the left, next to the logo. And vertically aligns the men with the top of the logo. 

![Home___Simplo](https://user-images.githubusercontent.com/3144571/89680897-84fddb00-d8b9-11ea-9120-91e2e6edb6cb.png)

My PR moves the logo to the center, when there is a logo present. If no logo, the title stays to left. I believe that I prefer this, mostly because the title is in a box and have that box next to the logo feels a little "off" to me. But, it works fine.

I also vertically aligned the logo, title, and menu to center on each other (instead of aligning to the top). Again, I think both could work. 

![Home___Simplo](https://user-images.githubusercontent.com/3144571/89681384-76fc8a00-d8ba-11ea-836a-517a5218ec2f.png)

I think that if you are happy with your current PR, you can mark this issue closed. Thanks for committing this, I think this is a big improvement either way. 

Once again, thanks for doing this theme. I think that the Backdrop ecosystem really needed a theme like this and I hope to see more themes of this nature in the future.

**Comment by indigoxela** [comment]
> Your layout of the header with the logo is different from mine. I expect you are aware of that.

Of course I am. :wink:

I tried several combinations of (different) logos and site names (and slogan) and think that in the end my variation is a better fit.

One of the concepts of Pelerine is that it should not _require_ a logo. But it should, of course, consider logo images. So, many thanks for your report.
