### ISSUE TITLE
Better default Background Image

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/pelerine#3]
I'm going to take a big risk here and suggest an alternative default background image. 

:-)

No offense, but I think that the default background is about the least flattering of the available backgrounds in the theme. 

I recommend changing the default to almost any other background - to give a better impression out of the box. 

(I think this is a great theme!)

Current default

![Home___Simplo](https://user-images.githubusercontent.com/3144571/89382600-bbbcd100-d6c0-11ea-8fcf-3f860c70807d.png)

**Comment by stpaultim** [comment]
Here is a PR - https://github.com/backdrop-contrib/pelerine/pull/4

For what it's worth. I'll understand if you close and ignore. It's a subjective choice and I may be wrong about this. 

:-)

Thanks for this theme. 

NOTE: I choose Orange Circles for my PR because I think it's a good solid background for logos and text. It's not my favorite, but I think it's a solid choice (not too light, not too dark), flexible, and does a better job of showcasing the theme. 

AFTER PR:

![Home___Simplo](https://user-images.githubusercontent.com/3144571/89382694-ddb65380-d6c0-11ea-91ad-86cdffe58da5.png)

**Comment by indigoxela** [comment]
Wow, you don't know that "orange circles" almost didn't make it in. :wink:

How about green-stripes or blue-abstract?

**Comment by stpaultim** [comment]
Well, as I mentioned Orange Circles isn't my favorite - but I was looking for one with a relative solid consistent background that doesn't obscure logo and text too much. Orange Circles does that, but so does green-stripes or blue-abstract. 

I think either of them would be an improvement. I'm not locked into Orange Circles at all - those are both good suggestions.
