### ISSUE TITLE
Allow custom css via user interface

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/pelerine#5]
Just a thought: maybe someone's interested in having the ability to set custom css rules in a textarea (no subtheme required, no need to touch any files on server).

If anyone's interested, please provide some feedback in this issue.

There's an experimental branch available for testing: [exp-custom-css](https://github.com/backdrop-contrib/pelerine/tree/exp-custom-css)

To test that locally, [download the zip file](https://github.com/backdrop-contrib/pelerine/archive/exp-custom-css.zip) and extract in Backdrops theme directory and rename it to "pelerine".

Here's a screenshot:

![screenshot-css-settings](https://user-images.githubusercontent.com/842066/89732380-d8edf880-da4e-11ea-902b-2a550a976ea7.png)

**Comment by stpaultim** [comment]
I like this feature and tested it out (briefly). It seems to work great. I endorse adding this feature to Pelegrine. 

This has me thinking, that I would like to add this feature to Tatsu, which then got me thinking that maybe this should be in core. Either in Basis or in core, such that it's available to all themes. But, that's another (probably controversial) discussion. :-)

**Comment by stpaultim** [comment]
Experimenting further and discovered that if you disable the module, while custom css is in place - the config file is deleted, but the css file in the files directory is not removed. 

Should disabling the module also delete the custom css file in the files directory?

On the other hand, if I turn off the custom css feature (but keep the module enabled), the css file is deleted. I wonder if that is necessary. If a user create a bunch of custom rules, they might want to disable them without loosing them, for testing purposes.

**Comment by indigoxela** [comment]
> Experimenting further and discovered that if you disable the module, while custom css is in place - the config file is deleted, but the css file in the files directory is not removed.

Oops, right, that's a job for hook_themes_disabled(), I guess.

> if I turn off the custom css feature (but keep the module enabled), the css file is deleted. I wonder if that is necessary.

That's by intention and a housekeeping thing. The code won't get applied anymore, so the css file should get removed, too. The next time a user toggles custom css on, they will start with an empty css file anyway, because it's not the file we read, but the config.

**Comment by indigoxela** [comment]
@stpaultim I thought it over and admit that you're right: users might toggle the "Add custom css" setting when experimenting. They wouldn't expect that all rules get deleted when turning it off.

Another finding: unlike modules themes have no hook to catch something when they get disabled. So there's no chance to remove the css file then.

**Comment by stpaultim** [comment]
@indigoxela - I do like that there is a way of cleaning up custom css file, but as I mentioned (and you seem to agree), simply turning off the feature might not the best way (at least without warning). 

One solution would be to simply add short text "disabling css rules will delete existing rules." 

I don't think that this issue is critical. I like the feature either way, I'm just sharing some thoughts on how it might be improved in simple ways. 

Also noting that this issue has implications for this core discussion: https://github.com/backdrop/backdrop-issues/issues/4459

**Comment by stpaultim** [comment]
@indigoxela - I tested this with your changes to NOT remove the css file and it works fine. I think I prefer this option, even if it does leave an extra file in the files folder. 

This also seems to fix a problem where the theme would sometimes try to delete the css file even when it did not exist.

**Comment by indigoxela** [comment]
A new theme version has been released which includes this feature. @stpaultim many thanks for testing and sharing your thoughts.
