### ISSUE TITLE
Security implications of custom css via user interface

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/pelerine#6]
What are the security implications of this?

Are we making sure that this file isn't used for anything other than css?

**Comment by indigoxela** [comment]
> Are we making sure that this file isn't used for anything other than css?

All html tags get stripped out before saving. I hope, that's enough from a security perspective.

To my knowledge there's no way to actually validate css code via php - at least no easy way. Adding a fully blown library to a theme is out of scope.

Apart from security:
We probably can't prevent people from adding wrong or broken css code (typos...). On the other hand the css file is not aggregated, so the damage will be limited.

**Comment by stpaultim** [comment]
I don't want to complicate this. I tried to add html and noticed that the tags were stripped out. I'm just curious about whether or not there is danger of JS (or something else) getting added this way (if that is a problem)?

I'm not too worried, because this feature is only available to trusted users anyway. I am not recommending any complicated changes, just asking the question to better understand the implications.
