### ISSUE TITLE
Fixed background images?

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/pelerine#8]
Most of the background images I've looked at don't repeat vertically as you scroll down the page, so there's a line where the image ends and then there's just a plain colour from that point on. A lot of the backgrounds you've been able to do this nicely with a similarly-coloured background, however some just cut off abruptly.

![image](https://user-images.githubusercontent.com/2385329/89977331-3cc22c80-dcae-11ea-941e-72d225bb5c76.png)
![image](https://user-images.githubusercontent.com/2385329/89977542-b35f2a00-dcae-11ea-8eed-d6e661f2d4f7.png)

What would you think of setting the backgrounds to be fixed, so they stay in place while the page scrolls? And if not doing this as default, what about a checkbox option for this in the theme settings?

**Comment by indigoxela** [comment]
> What would you think of setting the backgrounds to be fixed

I don't really like the idea, to be honest. The images Pelerine provides are pretty different and many of them won't look good with position fixed.

**Comment by ghost** [comment]
No problem.
