### ISSUE TITLE
Source for BG images?

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/pelerine#9]
Just curious, where'd you get the BG images? I really like them, so good job!
Maybe worth crediting the source in the README too...?

**Comment by indigoxela** [comment]
Why should I credit myself. :wink: 

Some of the images are inspired by images I found on pixabay (public domain), but I adapted them. One has been created with Gimp, several have been created with Inkscape.

**Comment by ghost** [comment]
Awesome, well done!
